using System;
using System.Collections.Generic;

#nullable disable

namespace Talleres.Infraestructure.DataBase.Context
{
    public partial class Cealumno
    {
        public string Alumno { get; set; }
        public string Empresa { get; set; }
        public int Sucursal { get; set; }
        public string Matricula { get; set; }
        public string Estatus { get; set; }
        public string Curp { get; set; }
        public string Rfc { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public bool DocumentacionCompleta { get; set; }
        public string PaisNacimiento { get; set; }
        public string EntidadNacimiento { get; set; }
        public bool DobleNacionalidad { get; set; }
        public string DobleNacionalidadPais { get; set; }
        public string Direccion { get; set; }
        public string DireccionNumero { get; set; }
        public string DireccionNumeroInt { get; set; }
        public string EntreCalles { get; set; }
        public string Delegacion { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string TelefonoParticular { get; set; }
        public string TelefonoOficina { get; set; }
        public string Extension { get; set; }
        public string TelefonoOtro { get; set; }
        public string TelefonoMovil { get; set; }
        public bool Smsauto { get; set; }
        public string Fax { get; set; }
        public bool PedirTono { get; set; }
        public string EMailParticular { get; set; }
        public bool EMailAutoParticular { get; set; }
        public string EMailTrabajo { get; set; }
        public bool EMailAutoTrabajo { get; set; }
        public string EMailOtro { get; set; }
        public bool EMailAutoOtro { get; set; }
        public string EMailInt { get; set; }
        public bool EMailAuto { get; set; }
        public string EstadoCivil { get; set; }
        public string Conyuge { get; set; }
        public DateTime? FechaMatrimonio { get; set; }
        public string Hijos { get; set; }
        public string Profesion { get; set; }
        public string EmpresaTrabajo { get; set; }
        public string EmpresaPuesto { get; set; }
        public string PueblosIndigenas { get; set; }
        public string LenguasIndigenas { get; set; }
        public string ViveCon { get; set; }
        public int? VivenCasa { get; set; }
        public string TrabajaCasa { get; set; }
        public string Religion { get; set; }
        public string Cuenta { get; set; }
        public string CuentaRetencion { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public string Descripcion3 { get; set; }
        public string Descripcion4 { get; set; }
        public string Descripcion5 { get; set; }
        public string Descripcion6 { get; set; }
        public string Descripcion7 { get; set; }
        public string Descripcion8 { get; set; }
        public string Descripcion9 { get; set; }
        public string Descripcion10 { get; set; }
        public DateTime? UltimoCambio { get; set; }
        public DateTime? FechaAlta { get; set; }
        public DateTime? FechaBaja { get; set; }
        public string NivelAcademico { get; set; }
        public string Programa { get; set; }
        public string SubPrograma { get; set; }
        public string PlanEstudio { get; set; }
        public string CicloEscolar { get; set; }
        public string Grupo { get; set; }
        public string ReferenciaBancaria { get; set; }
        public string FacturarCte { get; set; }
        public string Contrasena { get; set; }
        public string Contrasena2 { get; set; }
        public string Comentarios { get; set; }
        public string Situacion { get; set; }
        public DateTime? SituacionFecha { get; set; }
        public string SituacionUsuario { get; set; }
        public string SituacionNota { get; set; }
        public string Usuario { get; set; }
        public bool TieneMovimientos { get; set; }
        public bool FacturaMultiple { get; set; }
        public string Familia { get; set; }
        public string Relacion { get; set; }
        public string ListaPrecioEsp { get; set; }
        public byte[] SincroId { get; set; }
        public int? SincroC { get; set; }
        public int? NumCiclo { get; set; }
        public string Turno { get; set; }
        public string Cptestatus { get; set; }
        public string Cptcanal { get; set; }
        public string CptcanalDetalle { get; set; }
        public string CptcanalContacto { get; set; }
        public string CptdetalleSeguimiento { get; set; }
        public DateTime? CptfechaContacto { get; set; }
        public DateTime? CptfechaCita { get; set; }
        public int? CptplantelCita { get; set; }
        public string CptplantelNombreCita { get; set; }
        public string CptasistioCita { get; set; }
        public string CptcitaPersonal { get; set; }
        public string CptcitaPersonalNombre { get; set; }
        public DateTime? CptfechaCita2 { get; set; }
        public int? CptplantelCita2 { get; set; }
        public string CptplantelNombreCita2 { get; set; }
        public string CptasistioCita2 { get; set; }
        public string CptcitaPersonal2 { get; set; }
        public string CptcitaPersonalNombre2 { get; set; }
        public DateTime? CptfechaAlta { get; set; }
        public string CptnivelAcademico { get; set; }
        public string Cptprograma { get; set; }
        public string CptsubPrograma { get; set; }
        public string CptplanEstudio { get; set; }
        public string Cptturno { get; set; }
        public string Cptgrupo { get; set; }
        public bool? NoGenerarCuotasJob { get; set; }
        public string UsuarioSesionPortal { get; set; }
        public string PerfilPortal { get; set; }
        public string EstatusPortal { get; set; }
        public string MatriculaSep { get; set; }
        public bool? TieneBeca { get; set; }
        public bool? EsHijoMayor { get; set; }
        public bool? TieneTransporte { get; set; }
        public string NivelAcademicoNext { get; set; }
        public string ProgramaNext { get; set; }
        public string SubProgramaNext { get; set; }
        public string PlanEstudioNext { get; set; }
        public string CicloEscolarNext { get; set; }
        public int? NumCicloNext { get; set; }
        public string GrupoNext { get; set; }
        public string TurnoNext { get; set; }
        public string FacturarCte2 { get; set; }
        public string FacturarCte3 { get; set; }
        public string DesglosaTransporte { get; set; }
        public string Beca { get; set; }
        public decimal? Pbeca { get; set; }
        public bool? Convenio { get; set; }
        public string TipoConvenio { get; set; }
        public string Tutor { get; set; }
        public int? SucursalNext { get; set; }
        public string UltimaSituacion { get; set; }
        public bool? DesglosaEnFactura { get; set; }
        public string NivelAcademicoAnterior { get; set; }
        public string ProgramaAnterior { get; set; }
        public string PlanEstudioAnterior { get; set; }
        public string CicloEscolarAnterior { get; set; }
        public int? SucursalAnterior { get; set; }
        public bool? GeneroTrasporte { get; set; }
        public string Ruta { get; set; }
        public DateTime? FechaInicioClases { get; set; }
        public DateTime? FechaPago { get; set; }
        public decimal? FactorInc { get; set; }
        public int? EnviaAtlantis { get; set; }
        public bool? ColegituraPend { get; set; }
        public bool? GeneraMov { get; set; }
        public bool? GeneroBrinco { get; set; }
        public string PlanEstudioSituacion { get; set; }
        public double? Impaplaza { get; set; }
        public bool? GeneroColegiatura { get; set; }
        public bool? PierdeBecaPersonal { get; set; }
        public string UsoImagen { get; set; }
        public string Reinscripcion { get; set; }
    }
}
